version: '3.7'
services:
    homarr:
      container_name: homarr
      image: ghcr.io/ajnart/homarr:latest
      restart: unless-stopped
      networks:
        - proxy
      dns:
        - 192.168.0.110
      ports:
        - 7575:7575
      volumes:
        - ./.env/:/app/.env
        - ./configs:/app/data/configs
        - ./icons:/app/public/icons
        - "./app/integration.config.json:/app/integration.config.json"
        - /var/run/docker.sock:/var/run/docker.sock

networks:
  proxy:
    external: true
