# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets:
#       - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 50s

    static_configs:
         - targets: ['localhost:9090']

  # - job_name: 'cadvisor'

  #   # Override the global default and scrape targets from this job every 5 seconds.
  #   scrape_interval: 15s

  #   static_configs:
  #     - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s

    static_configs:
      - targets: ['192.168.0.110:9100']

  ## IDRAC
  - job_name: idrac
    scrape_interval: 60s
    scrape_timeout: 60s
    static_configs:
      - targets: ['idrac.lab.charj.dev']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: idrac.lab.charj.dev:9348

  # DNSMASQ
  - job_name: "dnsmasq"
    static_configs:
      - targets: ["192.168.0.110:9153"]

  # FIVEM
  - job_name: 'fxserver'
    scrape_interval: 30s
    metrics_path: /
    static_configs:
      - targets: ['192.168.0.110:3069']

  # Sons of The Forest
  - job_name: 'sons-of-the-forest'
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.0.110:9841']

  # Uptime Kuma
  - job_name: 'uptime'
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.0.110:3001']

  # Traefik
  - job_name: 'traefik'
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.0.110:8080']

  # Docker
  - job_name: 'docker'
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.0.110:9323']

  # Discord
  - job_name: 'discord'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.0.110:9324']

  # Supervisor Sense Hat
  - job_name: 'supervisor_sense'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['supervisor.lab.charj.dev:9101']

  # Supervisor
  - job_name: 'supervisor'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['supervisor.lab.charj.dev:9100']

  # VMWare
  - job_name: 'vmware'
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.0.110:9275']


  # Unifi
  - job_name: 'unifi'
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.0.110:9130']
